---

- hosts: all
  name: bring servers up to date.
  become: true
  pre_tasks:

  - name: patch servers
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes

- hosts: metal_servers, hypervisors, docker_containers
  name: install base packages and secure servers.
  become: true

  roles:
   # - role: base_server
   # - role: basic_hardening

- hosts: docker_containers
  become: true
  tags: docker
  roles: 
    - role: docker_engine

- hosts: docker_server01
  become: true
  roles: 
    - role: pihole
    - role: vaultwarden

- hosts: docker_server02
  become: true
  roles:
    - role: wg-easy
    - role: traefik
