http:
 #region routers 
  routers:
  
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.jhomelab.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox

    vaultwarden:
      entryPoints:
        - "https"
      rule: "Host(`vw.local.jhomelab.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: vaultwarden


    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.jhomelab.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pihole

    jellyfin:
      entryPoints:
        - "https"
      rule: "Host(`jellyfin.local.jhomelab.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jellyfin
  
#endregion
#region services
  services:

    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.5.15.100:8006"
          - url: "https://10.5.15.250:8006"
          - url: "https://10.5.15.200:8006"
        passHostHeader: true

    pihole:
      loadBalancer:
        servers:
          - url: "http://10.5.15.150:180"
        passHostHeader: true

    vaultwarden:
      loadBalancer:
        servers:
          - url: "http://10.5.15.150:280"
        passHostHeader: true

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://10.5.15.80:8096"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers